# Generated by Django 3.2.6 on 2021-08-30 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_home_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='title',
            field=models.CharField(default='hoge', max_length=256, verbose_name='タイトル'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='link',
            name='url',
            field=models.CharField(default='hogehoge', max_length=256, verbose_name='URL'),
            preserve_default=False,
        ),
    ]
